---
  - name: add default gateway for centralRouter
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=no

  - name: add default gateway for centralRouter
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      line: GATEWAY=192.168.255.1

  - name: Set up forward packages across routers
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      state: present

  - name: Reboot to apply network routes
    ansible.builtin.reboot:
...
